### ISSUE TITLE
EnemyAttackSystem cause a error when you killed a attacking enemy

### ISSUE THREAD

**Issue by lvcoc** [davidpol/SurvivalShooterECS#5] opened 2022-02-24 09:04 UTC
System.ArgumentException: The entity does not exist
Thrown from job: EnemyAttackSystem.<>c__DisplayClass_OnUpdate_LambdaJob0
This Exception was thrown from a job compiled with Burst, which has limited exception support. Turn off burst (Jobs -> Burst -> Enable Compilation) to inspect full exceptions & stacktraces.

I think maybe EnemyAttackData  linked to this enemy
Did anyone can help me to fix it?

**Comment by davidpol** [comment] 2022-02-26 09:42
Is this happening on the latest version of the project without any custom changes? I just upgraded it to Unity 2020.3.30 and Entities 0.17.0 and everything seems to be working fine.

Having said that, you might want to disable Burst compilation to get a complete stacktrace as suggested in the error message.

**Comment by lvcoc** [comment] 2022-02-28 06:47
> Is this happening on the latest version of the project without any custom changes? I just upgraded it to Unity 2020.3.30 and Entities 0.17.0 and everything seems to be working fine.
> 
> Having said that, you might want to disable Burst compilation to get a complete stacktrace as suggested in the error message.

Thanks！I will take a try！

**Comment by lvcoc** [comment] 2022-02-28 07:20
> Is this happening on the latest version of the project without any custom changes? I just upgraded it to Unity 2020.3.30 and Entities 0.17.0 and everything seems to be working fine.
> 
> Having said that, you might want to disable Burst compilation to get a complete stacktrace as suggested in the error message.

Sorry to bother you，but it still happened。
![image](https://user-images.githubusercontent.com/29865364/155941253-278a8ccc-7545-4e47-a5da-3e70659cadfd.png)

![image](https://user-images.githubusercontent.com/29865364/155940043-6f3c1101-02f5-4423-be5d-f24c056d3dcf.png)

![image](https://user-images.githubusercontent.com/29865364/155938419-8d55fbf0-634d-4cff-851c-e15128c423ac.png)
![image](https://user-images.githubusercontent.com/29865364/155938461-00650cff-02a5-4d5a-bd5e-f8a66770ba8f.png)
![image](https://user-images.githubusercontent.com/29865364/155941559-18ea86ad-14fc-4254-8013-f482ef6bf63a.png)
![image](https://user-images.githubusercontent.com/29865364/155941586-0f7a41a8-bbb7-470a-88ee-9c95101f5cb0.png)

**Comment by davidpol** [comment] 2022-02-28 07:30
I am closing this, as it is not happening on my end even when changing the spawn time.

**Closed as completed by davidpol** 2022-02-28 07:30 UTC

**Comment by davidpol** [comment] 2022-02-28 08:09
Thank you! I was finally able to reproduce this and hopefully the latest commit fixes the issue.

**Comment by lvcoc** [comment] 2022-02-28 08:11
> Thank you! I was finally able to reproduce this and hopefully the latest commit fixes the issue.

OK，thanks a lot anyway

**Comment by lvcoc** [comment] 2022-02-28 08:20
> Thank you! I was finally able to reproduce this and hopefully the latest commit fixes the issue.
YES！It fixed！love you！
